### ISSUE TITLE
Tutorial Page abap-env-rfc.md Issue. PROD

### ISSUE THREAD

**Issue by SAPDocs** [sap-tutorials/abap-core-development#13]
Tutorial issue found: [https://github.com/sap-tutorials/abap-core-development/blob/master/tutorials/abap-env-rfc/abap-env-rfc.md](https://github.com/sap-tutorials/abap-core-development/blob/master/tutorials/abap-env-rfc/abap-env-rfc.md)  - file path is not unique. Your tutorial was not created.

 Affected server: PROD

**Comment by julieplummer20** [comment]
Hi Patrick,
What exactly does this error message mean?
I have not encountered it before.


Thanks and best wishes,

Julie Plummer
Product Management
ABAP Development | SAP SE
Dietmar-Hopp-Allee 16 | D - 69190 Walldorf | Germany
Tel: +49 6227 760123
Email: ***@***.******@***.***>
Twitter: @julieplummer20<http://twitter.com/julieplummer20>
SAP Community: http://scn.sap.com/people/julie.plummer/

Or: Learn more about SAP Cloud Platform, ABAP Environment:
https://blogs.sap.com/2019/09/28/its-trialtime-for-abap-in-sap-cloud-platform/

**Comment by sepp4me** [comment]
Hello Julie,

I don't know. I've only assigned the problem to you during the housekeeping Maybe @jmmargo knows more about it.

Best regards,
  Patrick

**Comment by julieplummer20** [comment]
Hi Patrick, 
We resolved this last year so I'm closing this issue. 
Please let me know if you need any assistance from me.
BR Julie.
