### ISSUE TITLE
Create a SAP Fiori App and Deploy it to SAP BTP, ABAP Environment

### ISSUE THREAD

**Issue by KeerthiMohankumar** [sap-tutorials/abap-core-development#1330]
Hi
Tutorials: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html
--------------------------
Issue: Documentation update is required

Update 1:
At step 4 : Create list report object page
In step 3: Select List Report Page and click Next.
Screenshot has to be updated to the below attached one.
![image](https://github.com/sap-tutorials/abap-core-development/assets/107237818/95fdaf17-16c2-455c-8811-9b48f437727b)

Update 2:
At step 7: Check BSP library and SAP Fiori Launchpad app descriptor item in Eclipse.
Step 1: Screenshot has to be updated.
![image](https://github.com/sap-tutorials/abap-core-development/assets/107237818/6b02d483-1a11-4055-ac1f-55408c26fcfa)

Please update the same.

Labels:
Landscape Labels - trail2
Sprint Label: SCPTest-2310A
Scenario Label: SCPTest-fabap
Priority: Low

Thanks & Regards,
Keerthi

**Comment by mervey45** [comment]
Hi @KeerthiMohankumar ,

is fixed with PR: #1824.

Best regards, 
Merve
