### ISSUE TITLE
Create Database Table and Generate UI Service

### ISSUE THREAD

**Issue by bufiku** [sap-tutorials/abap-core-development#1392]
Tutorials: https://developers.sap.com/tutorials/abap-environment-rap100-generate-ui-service.html
--------------------------

In step 4, Generate transactional UI services, I noticed that you don't use the default names suggested by the  generator: 

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/bufik/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/bufik/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

Object | Suggested by   Generator | In   tutorial
-- | -- | --
Data Defnt | ZR_RAP100_ATRAV### | ZRAP100_R_TravelTP_###
Impl. Class | ZBP_R_RAP100_ATRAV### | ZRAP100_BP_TravelTP_###
BO   Projection | ZC_RAP100_ATRAV### | ZRAP100_C_TravelTP_###
Service Def | ZUI_RAP100_ATRAV###_O4 | ZRAP100_UI_Travel_###
Serv Binding | ZUI_RAP100_ATRAV###_O4 | ZRAP100_UI_Travel_O4_###

</body>

</html>

Could you at least explain why you deviate from the suggested names?
Thanks !

**Comment by mervey45** [comment]
Hi @bufiku ,

yes, we don't use the generated services names. We also added a hint section to this tutorial:

About Naming Conventions The main aspects of the naming conventions of SAP S/4HANA’s Virtual Data Model (VDM) are used in this exercise. More information on VDM can be found on the SAP Help portal: Here.

Attention Please make sure to replace all the name proposals in the wizard with the names provided below. Doing this is important to ensure the correctness of the code snippets provided in the following exercises.

Best regards, 
Merve
