### ISSUE TITLE
Enhance the Business Object Behavior With Unmanaged Internal Numbering

### ISSUE THREAD

**Issue by LucaNie** [sap-tutorials/abap-core-development#14]
Tutorials: https://developers.sap.com/tutorials/abap-environment-rap100-early-numbering.html
--------------------------

Write here how you think we can improve the tutorial ...

There is an error in [this](https://developers.sap.com/tutorials/abap-environment-rap100-early-numbering.html) tutorial. 
This snippet has been left in the code:
`field ( mandatory : create ) 
TravelID;`
It seems this overrides the internal numbering, still creating a popup to input an ID. The Tutorial should include a step to remove it.

**Comment by mervey45** [comment]
Hi @LucaNie ,

thank you for your feedback. This is described in step 1.3 of this tutorial. If you still face some issues, let me know.

Best regards, 
Merve
