### ISSUE TITLE
SAP BTP ABAP Environment: Create and Expose a CDS-Based Data Model 

### ISSUE THREAD

**Issue by AnitaDixit** [sap-tutorials/abap-core-development#1740]
Mission: https://developers.sap.com/mission.cp-starter-extensions-abap.html
--------------------------
Here in the step -
Create IAM App and business catalogue:
The test scope mentions that the Service Type to be picked is "OData V2 (Deprecated)" 
![image](https://github.com/sap-tutorials/abap-core-development/assets/8501821/06bd74a2-5c41-48a3-bcf4-49c594c0a182)

But it is actually not present in the dropdown list as shown :
<img width="1070" alt="OData_V" src="https://github.com/sap-tutorials/abap-core-development/assets/8501821/a9bffc66-8c4b-4290-ba23-145e61def3d4">

Please update the documentation as per the screenshot accordingly.

Labels:
Scenario label: SCPTest-fabap
Sprint Label: SCPTest-2312A
Landscape Label: trail2
Priority: Medium

Thanks & Kind Regards,
Anita

**Comment by mervey45** [comment]
Hi @AnitaDixit,

this is now fixed with PR: #1827.

Best regards, 
Merve
