### ISSUE TITLE
Test the Business API (BAPI) with An ABAP Console App

### ISSUE THREAD

**Issue by gregorwolf** [sap-tutorials/abap-core-development#1744]
Tutorials: https://developers.sap.com/tutorials/abap-environment-test-rfc.html
--------------------------

The code formatting of [step 7 ](https://developers.sap.com/tutorials/abap-environment-test-rfc.html#1b633250-3fcb-40c1-9af6-d8bf96dc40e5) is broken:

![Screenshot 2024-01-03 at 12 58 11](https://github.com/sap-tutorials/abap-core-development/assets/2639535/e4a3f3b1-6cb2-42ca-86b7-b5ff63ebc469)

**Comment by julieplummer20** [comment]
Hi Gregor, 
Thanks a lot for this. I have corrected it. The correction should be visible soon. 
Best wishes,
Julie.
