### ISSUE TITLE
Remote Function Module (RFC) - Get Data from an On-Premise System Using a Custom Entity

### ISSUE THREAD

**Issue by gregorwolf** [sap-tutorials/abap-core-development#1746]
Tutorials: https://developers.sap.com/tutorials/abap-environment-rfc-custom-entity.html
--------------------------

Hi @julieplummer20,

to get this tutorial working against the current [ABAP Platform Trial](https://hub.docker.com/r/sapse/abap-platform-trial) I had to do the following adjustments:

Define a Type for bapi_epm_max_rows

```ABAP
    TYPES:
      BEGIN OF bapi_epm_max_rows,
        bapimaxrow TYPE bapimaxrow,
      END OF bapi_epm_max_rows.
```

and use it in:

```ABAP
          DATA ls_maxrows TYPE bapi_epm_max_rows.
```

which I then fill as

```ABAP
          ls_maxrows-bapimaxrow = lv_skip + lv_top.
```

The fields ProductId and CurrencyCode of the DDL Structure had to be renamed to Product_Id and Currency_Code. 

Best Regards
Gregor

**Comment by julieplummer20** [comment]
Hi Gregor, 
Thanks a lot; this is really helpful.
I will update the tutorial accordingly.
Best wishes,
Julie.

**Comment by julieplummer20** [comment]
Done - changes should be visible in next 24 hours
