### ISSUE TITLE
Push Your ABAP Source Code from SAP BTP, ABAP Environment to a GitHub Repository using abapGit

### ISSUE THREAD

**Issue by rcaziraghi** [sap-tutorials/abap-core-development#1752]
Tutorials: https://developers.sap.com/tutorials/abap-environment-abapgit-transfer.html
--------------------------

Hello,

I recently revisited this tutorial and encountered a couple of additional screens that I don't recall seeing previously (Branch/package and folder logic selection). This could be specific to my repository, which is brand new, or it might indicate changes since the last time I completed this tutorial. If you confirm that there have been updates, I would be happy to create a pull request to include these new screens in the tutorial.

I look forward to your response.

Best regards,
Rafael

**Comment by mervey45** [comment]
Hi @rcaziraghi ,

I tested this tutorial and the steps are still the same. Maybe you need to try it out again. 
The respository I created is private.

If you still encounter issues, feel free to contact us again.

Best regards, 
Merve
