### ISSUE TITLE
Create an HTTP Service in SAP BTP ABAP Environment

### ISSUE THREAD

**Issue by larryhardin01** [sap-tutorials/abap-core-development#1784]
Tutorials: https://developers.sap.com/tutorials/abap-environment-create-http-service.html
--------------------------

Write here how you think we can improve the tutorial ...
I am not able to complete Step 9 in the tutorial. 
It is not clear at all WHERE step 2 should be executed and the screenshot looks like it is not happening in Eclipse.  This step really requires more explanation such as, "Next go to XXX and navigate to YYY"

**Comment by julieplummer20** [comment]
Hi [larryhardin01](https://github.com/larryhardin01), 
Thanks for getting in touch. I don't quite  understand. Step 9.1 starts "Open the dashboard for your system." It also shows you the URL for that dashboard. If you click on that, it should take you straight to the dashboard in the browser. I have changed "dashboard" to "SAP Fiori launchpad" and changed Step 9.2 slightly. 

Best wishes,
Julie Plummer.
