### ISSUE TITLE
Create an ABAP Database Table and Relevant ABAP Dictionary Objects

### ISSUE THREAD

**Issue by chbob95** [sap-tutorials/abap-core-development#1785]
Tutorials: https://developers.sap.com/tutorials/abap-dev-create-table.html
--------------------------

Please add the bank name to the primary key to make it more realistic

**Comment by julieplummer20** [comment]
Hi chbob95, 
Thanks for this. I have now updated the tutorial.
Best wishes,
Julie Plummer.
