### ISSUE TITLE
Event Consumption in ABAP Development Tools for Eclipse

### ISSUE THREAD

**Issue by gregorwolf** [sap-tutorials/abap-core-development#1786]
Tutorials: https://developers.sap.com/tutorials/abap-environment-event-enablement-consumption.html
--------------------------

I think the better name for this tutorial would be "Event Consumption in ABAP Environment".

**Comment by julieplummer20** [comment]
Agreed!
Done. 
Many thanks Gregor
BR Julie Plummer.
