### ISSUE TITLE
Create Business Configuration Maintenance Object

### ISSUE THREAD

**Issue by fabianlupa** [sap-tutorials/abap-core-development#1787]
Tutorials: https://developers.sap.com/tutorials/abap-environment-business-configuration-object.html
--------------------------

In step 5.3 the link to the naming conventions doesn't work. I get a login page for help.sap.com (?). After logging in the site doesn't load or I get a no authorization error.

> The system generates a proposal for all input fields based on the description of the table by following these [naming conventions](https://help.sap.com/viewer/923180ddb98240829d935862025004d6/Cloud/en-US/8b8f9d8f3cb948b2841d6045a255e503.html). If you receive an error message stating that a specific object already exists, change the corresponding name in the wizard.

**Comment by sepp4me** [comment]
@fabianlupa  Link works fine for me, maybe a temporary problem.
Could you please try again? Thanks

**Comment by sepp4me** [comment]
Yes its the same.
I will change the link in the tutorial to https://help.sap.com/docs/abap-cloud/abap-rap/naming-conventions-for-development-objects?version=sap_btp
Does that work for you?

**Comment by fabianlupa** [comment]
Yes, that would fix the issue for me

**Comment by sepp4me** [comment]
done https://github.com/sap-tutorials/abap-core-development/pull/1829
