### ISSUE TITLE
Create a SAP Fiori App and Deploy it to SAP BTP, ABAP Environment

### ISSUE THREAD

**Issue by serdarbdn** [sap-tutorials/abap-core-development#1834]
Tutorials: https://developers.sap.com/tutorials/abap-environment-deploy-cf-production.html
--------------------------

Deployment fails when the namespace field is left blank.

**Comment by mervey45** [comment]
Hi @serdarbdn , 

can you please send a screenshot with the error message, or with your input.

Best regards, 
Merve

**Comment by mervey45** [comment]
Hi @serdarbdn ,

we didn't hear from you, so we are closing this issue. If you are still having issues, please open a new ticket.

Best regards, 
Merve
