### ISSUE TITLE
Providing Authorization Control for a Business Configuration Maintenance Object

### ISSUE THREAD

**Issue by flopezmm** [sap-tutorials/abap-core-development#1849]
Tutorials: https://developers.sap.com/tutorials/abap-environment-authorization-control.html
--------------------------

The Step 3 of this tutorial talks about a configuration to be done in Workzone. It actually is done within the Fiori Launchpad of the SAP ABAP Runtime Environment where the objects are being created.

The role mentioned SAP_BR_ADMINISTRATOR - Administrator is also part of this environment.

![Step3](https://github.com/sap-tutorials/abap-core-development/assets/22063483/c64c0b6b-3f03-4f39-ad88-5e2010c2ed35)

**Comment by sepp4me** [comment]
My understanding is that SAP Build Work Zone, standard edition is the new name of SAP Launchpad in BTP

https://community.sap.com/t5/technology-blogs-by-sap/sap-launchpad-service-is-now-sap-build-work-zone-standard-edition/ba-p/13569593
_Please note: SAP Launchpad service has been rebranded to ´SAP Build Work Zone, standard edition´_
