### ISSUE TITLE
Create a Custom RAP Business Object to Trigger Purchase Requisitions API

### ISSUE THREAD

**Issue by Neil057** [sap-tutorials/abap-core-development#19]
Tutorials: https://developers.sap.com/tutorials/abap-s4hanacloud-procurement-purchasereq-shop.html
--------------------------

I can't fix the issue when going to Step6.Enhance behavior definition of data model
The problem as below

Error line: event sendPurchaseRequisitionDetails parameter zabs_purchaserequisition;
Problems Description: Type "zabs_purchaserequisition" is unknown.

I think some steps are missing.

**Comment by mervey45** [comment]
Hi, 

this issue has been fixed.

Best regards, 
Merve
