### ISSUE TITLE
Define and Expose a CDS-Based Travel Data Model

### ISSUE THREAD

**Issue by frankmeertens** [sap-tutorials/abap-core-development#2455]
Tutorials: https://developers.sap.com/tutorials/abap-environment-data-model.html
--------------------------

The step 4 that creates the service binding has a difference between the instruction and the screenshot. Instruction refers to binding type OData V2, while the screenshot refers to OData V4.

**Comment by mervey45** [comment]
Hi @frankmeertens ,

thank you for your feedback. This is fixed with PR: #2463.

Best regards, 
Merve
