### ISSUE TITLE
Enhance the Business Object Data Model and Enable OData Streams

### ISSUE THREAD

**Issue by mydoghasfleas** [sap-tutorials/abap-core-development#2458]
Tutorials: https://developers.sap.com/tutorials/abap-environment-rap100-enhance-data-model.html
--------------------------

Under step 3, where it says: "with the addition provider contract transactional_query", the text "provider contract" is part of the code snippet and should be formatted accordingly, so that the complete code snippet reads "provider contract transactional_query", i.e. `provider contract transactional_query`.

![image](https://github.com/sap-tutorials/abap-core-development/assets/125179869/e044ff05-28c4-473d-b30e-a9a48a5db67f)

**Comment by mervey45** [comment]
Hi @mydoghasfleas ,

thank you for your feedback. We just wanted to highlight **transactional_query**, that's why this is formatted this way. Provider contract is just added as a word. The code snippet is not part of the info box. There are only words, that are highlighted.

Best regards, 
Merve
