### ISSUE TITLE
Enhance the Business Object Data Model and Enable OData Streams

### ISSUE THREAD

**Issue by mydoghasfleas** [sap-tutorials/abap-core-development#2459]
Tutorials: https://developers.sap.com/tutorials/abap-environment-rap100-enhance-data-model.html
--------------------------

Step 3.4; the code samples do not correspond to the screenshots; they are missing `, useForValidation: true` in each case.

**Comment by mervey45** [comment]
Hi @mydoghasfleas , 

thank you for your feedback. This issue is fixed with PR:  #2463.

Best regards, 
Merve
