### ISSUE TITLE
Create Database Table and Generate UI Service

### ISSUE THREAD

**Issue by gueney0** [sap-tutorials/abap-core-development#2464]
Tutorials: https://developers.sap.com/tutorials/abap-environment-rap100-generate-ui-service.html
--------------------------

Write here how you think we can improve the tutorial ...

Hello colleagues,

I just tried the Create Database Table and Generate UI Service task and I might do a mistake but step 4 is not working properly. I maintained the Configure Generator tab as explained in the task. But when I try to finsih the step the activation fails with an error message which is not describing the error exactly. I tried it several times. Evendough the error message appears, the objects still get created. Then I tried step 5 but because the objects are not activated due to the error message in step 4 I am not able to execute the publich button in step 5 because now there are no default authorization values maintained. 

I tried to execute step 4 with the dafault values in the configure generator tab again and then it worked. Also the publish button worked and an UI was launched in the browser but now because of the presettings in the steps before the go button is not working and no data is loaded. 

Best regards, 
Güney

**Comment by mervey45** [comment]
Hi @gueney0 , 

can you please share a screenshot of all generated artefacts in your project explorer? So that I can check everything.

Thank you.

Best regards, 
Merve

**Comment by mervey45** [comment]
Hi @gueney0 , 

we are closing this ticket, since you didn't reply. If you are still facing some issues, please open a ticket again.

Best regards, 
Merve
