### ISSUE TITLE
Enhance Behavior With Action and Validation

### ISSUE THREAD

**Issue by fabienlg** [sap-tutorials/abap-core-development#2489]
Tutorials: https://developers.sap.com/tutorials/abap-environment-behavior-action.html
--------------------------

Hello, nice tutorial thanks.

Just to notify you that links in step 12 (except the last one for Open SAP) are dead.

**Comment by mervey45** [comment]
Hi @fabienlg , 

thank you for your comment. The link is working now.

Best regards, 
Merve
