### ISSUE TITLE
Enhance Behavior With Action and Validation

### ISSUE THREAD

**Issue by CimermanDenis** [sap-tutorials/abap-core-development#2491]
Tutorials: https://developers.sap.com/tutorials/abap-environment-behavior-action.html
--------------------------

OData V4 service binding does not work without draft and there is no draft implemented in this tutorial. Therefore the students cannot see the "create" etc. buttons.

**Comment by mervey45** [comment]
Hi @CimermanDenis , 

thank you for your message. I will update it to Odata v2 again. 

Best regards, 
Merve
