### ISSUE TITLE
Create Database Table and Generate UI Service - Step 4 Fails on activation of service binding

### ISSUE THREAD

**Issue by mydoghasfleas** [sap-tutorials/abap-core-development#2492]
Tutorials: https://developers.sap.com/tutorials/abap-environment-rap100-generate-ui-service.html
--------------------------

I am doing the tutorial for the second time, **using the SAP BTP Trial (as before)**, and this time, for some reason, I am finding that the activation fails at the end.

The service binding ZRAP100_UI_TRAVEL_O4_### activation fails with a message that "Usage of ZRAP100_UI_Travel_### not permitted".

**(Obviously using my own group number, not "###"!)**

I find that I now have to change the service definition to add `@AbapCatalog.extensibility.extensible: true`, then release it with Contract C0.

Thereafter, I have to delete and recreate the service binding in order to be able to activate it.

Not sure whether this is something specific to me, or whether something has changed on the system since the previous time I did the tutorial.

**Comment by mervey45** [comment]
Hi @mydoghasfleas , 

thank you for your message. The generator had an update. Therefore there are some steps added to this tutorial. It should work now.

Best regards, 
Merve
