### ISSUE TITLE
Implement a Custom Entity and Query Implementation Class

### ISSUE THREAD

**Issue by AWaggy** [sap-tutorials/abap-core-development#2494]
Tutorials: https://developers.sap.com/tutorials/abap-environment-a4c-create-custom-entity.html
--------------------------

The link does not work for me and my colleagues.

**Comment by julieplummer20** [comment]
Hi,
Do you mean this link: 
[https://developers.sap.com/tutorials/abap-environment-a4c-create-custom-entity.html](https://developers.sap.com/tutorials/abap-environment-a4c-create-custom-entity.html)

I have tested this link. It works here.
Can you access other links in the Tutorial Navigator?

Have you tried clearing your browser cache; then trying a different browser?

If so, then I can offer you this PDF of the tutorial.
[abap-environment-a4c-create-custom-entity.html.pdf](https://github.com/user-attachments/files/15787024/abap-environment-a4c-create-custom-entity.html.pdf)

Best wishes,
Julie Plummer.
ABAP PM.

**Comment by AWaggy** [comment]
Dear Julie,

sorry for the "minimalist" problem description.
I mean the three links under the section "This tutorial is based on:".
We first have to login at "accounts.sap.com", then "Sorry We couldn't find that page." appears.

We tried with Chrome and Edge and cleared all the caches.
Best regards,
Andreas

**Comment by julieplummer20** [comment]
Also: Have you tried logging in with your P-User?

**Comment by AWaggy** [comment]
Dear Julie,
my P-User has the same behaviour.
I use the Keeper plugin to manage my credentials. I tried the following:
In case I remove 'version=sap_btp%3Flocale%3Den-US&version=Cloud&state=PRODUCTION' from the URL
'https://help.sap.com/docs/ABAP_Cloud/f055b8bf582d4f34b91da667bc1fcce6/6436a50d7d284f01af2cca7a76c7116a.html?version=sap_btp%3Flocale%3Den-US&version=Cloud&state=PRODUCTION', the page is displayed correctly.

**Comment by julieplummer20** [comment]
Hi Andreas, Thanks a lot for this. I'll clean up the link and republish. 
I will now close the issue; the changes should be available in 48-72 hours.

Best wishes,
Julie
