### ISSUE TITLE
Create Behavior Definition for Managed Scenario

### ISSUE THREAD

**Issue by CimermanDenis** [sap-tutorials/abap-core-development#2496]
Tutorials: https://developers.sap.com/tutorials/abap-environment-behavior.html
--------------------------

There will be no CREATE button in the Preview (and also not in a deployed app) unless you activate the draft handling in your business object. These steps ("use draft" in projection behavior definition, "with draft", total etag and draft actions in data view behavior definition, create draft table...) are missing in the tutorial. I spent half a day investigating but no regrets - I learnt so much!

**Comment by mervey45** [comment]
Hi @CimermanDenis , 

thank you for your message. We will switch to OData V2, then this problem should be solved.

Best regards, 
Merve
