### ISSUE TITLE
Documentation Issue for creating ABAP Package

### ISSUE THREAD

**Issue by SoumyaGyanapnor** [sap-tutorials/abap-core-development#2499]
Tutorials: https://developers.sap.com/tutorials/abap-environment-persistence.html
--------------------------
Issue: Regarding Documentation Update

Here, observation: In the documentation it is given that when we create ABAP package after giving mandatory fields , it will be saved in the Favorites Objects. But when we create the ABAP Package it will be saved in the Favorite Packages.

Steps to reproduce:
Create Table Persistence and Generate Data
STEP 1: Create ABAP package
     1.2: Create new ABAP Package and provide all the necessary details
     1.3: Select Create new request and click on Finish
     1.4: Package will be added to the Favorite Packages

![CDS_ADT_SS](https://github.com/sap-tutorials/abap-core-development/assets/124772107/11115db1-0efd-47e6-919e-740476be4903)

Kindly change the documentation.

Labels to be added:
Scenario Label- SCPTest-fabap
Landscape Labels - trail2
Sprint Label: SCPTest-2406A
Priority: Low

Thanks and Regards,
Soumya

**Comment by mervey45** [comment]
Hi @SoumyaGyanapnor , 

thank you for your comment. This is now updated.

Best regards, 
Merve
