### ISSUE TITLE
Connect to Your On-Premise System from SAP BTP, ABAP Environment Using RFC

### ISSUE THREAD

**Issue by leo8086** [sap-tutorials/abap-core-development#2520]
Tutorials: https://developers.sap.com/tutorials/abap-env-rfc.html
--------------------------
Hello,

In Step 7 "Create communication system" it states: Now, you need to create the necessary communication artifacts in Fiori Launchpad (of the BTP instance)

I cannot find the Fiori Launchpad on my BTP. As I understand, it was replaced by "SAP Build Workzone" but I cannot find the option to define communication artifacts.

Please help me,

**Comment by julieplummer20** [comment]
Hi Leo,
"Communication artifacts" is an umbrella term for : Comm. Arrangement, Comm. System, Comm. User etc.
For these apps to appear, you need to have the System Administrator assign the business role SAP_BR_DEVELOPER to your user.
I will update the term "Fiori Launchpad".
There seems to be an issue, that the Prerequisites have been deleted. I will investigate that.
In the meantime, here they are:
- You have set up SAP Business Technology Platform (BTP), ABAP Environment, for example by using the relevant booster: [Using a Booster to Automate the Setup of the ABAP Environment](https://help.sap.com/viewer/65de2977205c403bbc107264b8eccf4b/Cloud/en-US/cd7e7e6108c24b5384b7d218c74e80b9.html)
- **Tutorial**: [Set Up SAP BTP, ABAP Environment and create Your First Console Application](abap-environment-trial-onboarding), for a licensed user, steps 1-2
-	You have a user in an ABAP on-premise system. Examples of such on-premise systems include:
    - [AS ABAP developer edition, latest version](https://blogs.sap.com/2019/07/01/as-abap-752-sp04-developer-edition-to-download/) or:
    - [SAP S/4HANA 1809 fully activated appliance](https://blogs.sap.com/2018/12/12/sap-s4hana-fully-activated-appliance-create-your-sap-s4hana-1809-system-in-a-fraction-of-the-usual-setup-time/)
- You have connected **SAP Cloud Connector**, to your BTP subaccount
- You have assigned the business role **`SAP_BR_DEVELOPER`** to your user; you will need it to create communication artifacts

Best wishes,
Julie Plummer.

**Comment by leo8086** [comment]
hi Julie, Thank you for the reply.

I'm still confused about the phrase "Fiori Launchpad (of the BTP instance)", it means that somewhere in my BTP I can access that?

My situation is:

- I have a BTP account (trial)
- I have setup ABAP environment and Eclipse
- My SAP system is ERP 6.0 EHP7
- I have connected the cloud connector on my SAP on premise system
- I have successfully followed the tutorial until Step 7

Now I'm stuck because inside my BTP cockpit I can't seem to find an option similar to the one shown in the tutorial to create communications artifacts.

Am I missing something?

Thanks

**Comment by julieplummer20** [comment]
Hi Leo, 
Since you have accessed ABAP Environment in Eclipse:
1. In Project Explorer, right-click on your project - ie on your ABAP Environment instance.
2. Choose Properties > ABAP Development > copy the URL pointing to the ABAP Environment instance.
3. Paste that in your browser.
This screenshot shows the URL. Does this help?

Best wishes
Julie.

[URL for Fiori launchpad](https://developers.sap.com/tutorials/abap-environment-create-abap-cloud-project/jcr:content.github-proxy.1698673202.file/project52.png )

**Comment by leo8086** [comment]
Thanks Julie, 
I was able to find and open the link.

Unfortunately, in the new screen, I cannot find the communication manager, or anything else of that ilk, please see below:

![img](https://github.com/user-attachments/assets/5e4073aa-93ce-41ca-b9cc-d8db5491301e)

Futhermore, in my BTP instance I've every role assigned to my account

And this is the image shown in step 7 of the guide:

![Img2](https://github.com/user-attachments/assets/c283a0cc-2e14-4424-84d6-da75da655ed5)
![Img3](https://github.com/user-attachments/assets/c96e003d-6210-4863-8d49-d4b65c5c01a4)

Thanks again for your support.

**Comment by leo8086** [comment]
> 1. You may need to define the relevant homepage structure that should be exposed to the launchpad. In Manage Launchpad Settings, set the relevant value for EXPOSURE_HOMEPAGE_STRUCTURE. See [Manage Launchpad Settings](https://help.sap.com/docs/btp/user-interface-configurations/manage-launchpad-settings).

Hi Julie, don't worry.
I tried to check the "Manage Launchpad Settings" app, but it says "SAP S/4HANA Cloud" is required:
![image](https://github.com/user-attachments/assets/99508419-6865-4eca-aee1-34bbebb06cb5)

My system is SAP ERP 6.0 EHP7, at this point I'm safe to assume that this connection cannot be done?

Thanks,
Leonardo

**Comment by julieplummer20** [comment]
Hi Leonardo,
Thanks for the quick response. However, the tutorial refers to the BTP ABAP Environment system (ie "Steampunk") or S/4HANA Cloud system that you're using to **connect** to the ERP 6.0 system. All the Communication artifacts - Arrangement, System, User - are created on the Steampunk / S4HANA Cloud system. So the version of the ERP 6.0 (on-premise) system is not the issue here.
Let me know how you get on.
Best wishes,
Julie Plummer.

**Comment by leo8086** [comment]
> Hi Leonardo, Thanks for the quick response. However, the tutorial refers to the BTP ABAP Environment system (ie "Steampunk") or S/4HANA Cloud system that you're using to **connect** to the ERP 6.0 system. All the Communication artifacts - Arrangement, System, User - are created on the Steampunk / S4HANA Cloud system. So the version of the ERP 6.0 (on-premise) system is not the issue here. Let me know how you get on. Best wishes, Julie Plummer.

HI Julie, thanks for the clarification.
In summary, this is my instance of ABAP Environment (Shared)
![image](https://github.com/user-attachments/assets/93f0b1dc-b84c-47e5-a506-5df5506dbcf2)
When I click the instance, this is the Launchpad i see.
![image](https://github.com/user-attachments/assets/8f9ff658-841d-4d6d-87fc-cc6d6de4f64e)
Here I don't have the app "Manage launchpad settings" nor "Communication arrangements":
![image](https://github.com/user-attachments/assets/fcf6860c-fde7-409b-bccd-f802c9d95bf5)
![image](https://github.com/user-attachments/assets/0b81ad4f-f7bd-4a7f-aa5a-e1e4ae82f272)
This are my roles in BTP:
![image](https://github.com/user-attachments/assets/ffaa7f2e-6041-4d66-b1d7-17abb8812215)

Maybe the problem is that ABAP Environment instance is Shared? But that's the only subscription that I'm allowed to use on trial account.

Thanks for your patience,
Leonardo

**Comment by leo8086** [comment]
Yes I missed that information, sorry.
Unfortunately, at the moment, I cannot access Free-Tier,
Thanks for everything.
