### ISSUE TITLE
Create an ABAP Database Table and Relevant ABAP Dictionary Objects

### ISSUE THREAD

**Issue by francisco-milan** [sap-tutorials/abap-core-development#2522]
Tutorials: https://developers.sap.com/tutorials/abap-dev-create-table.html
--------------------------

Write here how you think we can improve the tutorial ...

In **STEP 11** we see this: **"@AbapCatalog.dataMaintenance : #NOT_ALLOWED"**

![image](https://github.com/user-attachments/assets/eef91458-cce6-4d77-8c50-c5b8e4e2a043)

If we create the table with this code, when we try to complete **STEP 16** we get an error message.

![image](https://github.com/user-attachments/assets/5ff93366-cf52-486a-a1d2-5db26ff87d94)

![image](https://github.com/user-attachments/assets/663431cd-3967-4942-894a-3a66bca65f3f)

In order to fix this issue we need to change **Line 5** of the code to this:

![image](https://github.com/user-attachments/assets/91d4282d-8b17-4b56-9fa8-2d990f878bfd)

**Comment by julieplummer20** [comment]
Hi Fransisco,
Apologies - you are right of course. I have updated the tutorial - this should be visible soon.
Best wishes 
Julie Plummer.
