### ISSUE TITLE
Learn about the ABAP Data Dictionary

### ISSUE THREAD

**Issue by seVladimirs** [sap-tutorials/abap-core-development#2528]
Tutorials: https://developers.sap.com/tutorials/abap-dev-learn-ddic.html
--------------------------

There is no image in Step 1, see the screenshot
<img width="1002" alt="image" src="https://github.com/user-attachments/assets/68cbb1b9-bdca-4df5-96d2-223eff27b68f">

**Comment by julieplummer20** [comment]
Apologies; this is now fixed and should appear soon.
Best wishes,
Julie.
