### ISSUE TITLE
Set SAP BTP, ABAP Environment as a Content Provider for SAP Build Work Zone, standard edition

### ISSUE THREAD

**Issue by gregorwolf** [sap-tutorials/abap-core-development#2529]
Tutorials: https://developers.sap.com/tutorials/abap-environment-lp-service-content-provider.html
--------------------------

Step 3 - Select Roles for Exposure to SAP Build Work Zone, standard edition

Hello,

I'm trying to check the "Exposed to SAP BTP" checkbox. But it's not possible to check it. I had to create a new custom role from the SAP_BR_ADMINISTRATOR template and there I was able to activate the "Exposed to SAP BTP" checkbox. I think the tutorial needs an update.

Best Regards
Gregor

**Comment by AchimSeubert** [comment]
Hello,
this is fixed. The fix can be seen already in the tutorial.
Thanks for the feedback and best regards, Achim
