### ISSUE TITLE
Create an ABAP Database Table and Relevant ABAP Dictionary Objects

### ISSUE THREAD

**Issue by seVladimirs** [sap-tutorials/abap-core-development#2530]
Tutorials: https://developers.sap.com/tutorials/abap-dev-create-table.html
--------------------------

Step 10 - Test yourself is empty block
<img width="1920" alt="image" src="https://github.com/user-attachments/assets/0e5acf56-a967-41a6-abbe-fc31409c16b4">

**Comment by julieplummer20** [comment]
Hi , Apologies, now fixed.
Thanks and best wishes,
Julie Plummer.
