### ISSUE TITLE
Create an ABAP Database Table and Relevant ABAP Dictionary Objects

### ISSUE THREAD

**Issue by michaelnicholls** [sap-tutorials/abap-core-development#2532]
Tutorials: https://developers.sap.com/tutorials/abap-dev-create-table.html
--------------------------

The task to create an ABAP database table etc doesn's allow using F8 to preview the table contents, at least with my version of ADT. It looks like the dataMaintenance: #NOT_ALLOWED causes an ADT error about not using standard tools for previewing. Changing to #RESTRICTED allows the preview to work OK.

**Comment by michaelnicholls** [comment]
Duplicate

**Comment by julieplummer20** [comment]
Hi Michael,
You're right - my apologies.
This is fixed and should appear soon.
Best wishes,
Julie Plummer.
