### ISSUE TITLE
Provision Users into your SAP BTP ABAP Environment

### ISSUE THREAD

**Issue by bmaciag** [sap-tutorials/abap-core-development#2536]
Tutorials: https://developers.sap.com/tutorials/abap-environment-ips.html
--------------------------

Can we somehow add a link or better description about the prerequisite "BR_IPS_TUTORIAL_DEVELOPER" ?

**Comment by Liebherr** [comment]
Hi bmaciag,
honestly, I do not know what you are missing at the current prerequisite which states: "An SAP Fiori launchpad business role for custom ABAP development created from template SAP_BR_DEVELOPER, as for example in this tutorial BR_IPS_TUTORIAL_DEVELOPER". Would be happy to have more details about your idea.
Regards
Ulrike

**Comment by bmaciag** [comment]
Now when reading it carefully for the second time I got the point. Thx for clarifying
