### ISSUE TITLE
Create an ABAP Core Data Services (CDS) View in SAP BTP, ABAP Environment

### ISSUE THREAD

**Issue by francisco-milan** [sap-tutorials/abap-core-development#2537]
Tutorials: https://developers.sap.com/tutorials/abap-environment-create-cds-mde.html
--------------------------

Write here how you think we can improve the tutorial ...

Hello,

I wanted to provide some feedback regarding the code in Step 9. I encountered an issue when I copied and pasted the original version; it didn’t work as expected. After some adjustments, I was able to get it functioning correctly.

Original Version:

    @UI           : {
    lineItem      : [{position: 10, importance: #HIGH}]
    }
    key TravelID;
    
    @UI           : {
          lineItem      : [{position: 15, importance: #HIGH}]
          }
    AgencyID,
    
    @UI           : {
          lineItem      : [{position: 20, importance: #HIGH}]
          }
    CustomerID,
    
    @UI           : {
          lineItem      : [{position: 30, importance: #HIGH}]
          }
    BeginDate,
    
    @UI           : {
          lineItem      : [{position: 40, importance: #HIGH}]
          }
    EndDate,
    
    BookingFee,
    
    @UI           : {
          lineItem      : [{position: 50, importance: #HIGH}]
          }
    TotalPrice,

Proposed Version:

    @UI           : { 
        lineItem      : [{position: 10, importance: #HIGH}]
    }
    key TravelID,
    
    @UI           : {
        lineItem      : [{position: 15, importance: #HIGH}]
    }
    AgencyID,
    
    @UI           : {
        lineItem      : [{position: 20, importance: #HIGH}]
    }
    CustomerID,
    
    @UI           : {
        lineItem      : [{position: 30, importance: #HIGH}]
    }
    BeginDate,
    
    @UI           : {
        lineItem      : [{position: 40, importance: #HIGH}]
    }
    EndDate,
    
    @Semantics.amount.currencyCode: 'CurrencyCode'
    BookingFee,
    
    @Semantics.amount.currencyCode: 'CurrencyCode'
    @UI           : {
        lineItem      : [{position: 50, importance: #HIGH}]
    }
    TotalPrice,

Key Differences:
The main differences in my proposed version include the addition of **@Semantics.amount.currencyCode: 'CurrencyCode'** for both **BookingFee** and **TotalPrice** (following the instructions on STEP 3). Additionally, I corrected the semicolon after **"key TravelID"** to a comma, ensuring proper syntax for the code structure.

I hope this feedback is helpful! Thank you for your efforts in creating this Tutorial.

Best regards,

Francisco Milan.

**Comment by julieplummer20** [comment]
Hi Fransisco, Yes, this code is added in step 11, but you are not the first to have an issue. I will edit the code appropriately.
Thanks a lot,
JUlie Plummer.

**Comment by julieplummer20** [comment]
Hi Fransisco,
I've corrected this; it should be available soon.
Many thanks for this spot!
Best wishes,
Julie.
