### ISSUE TITLE
Enhance an ABAP Core Data Services (CDS) View in SAP Business Technology Platform (BTP) ABAP Environment

### ISSUE THREAD

**Issue by francisco-milan** [sap-tutorials/abap-core-development#2539]
Tutorials: https://developers.sap.com/tutorials/abap-environment-enhance-cds-view.html
--------------------------

Write here how you think we can improve the tutorial ...

 I noticed that the code snippet from Step 4.4, is not present in Step 5 where we are supposed to check our code.

![image](https://github.com/user-attachments/assets/86766feb-2515-46eb-bcfc-deca4025c2bc)

I think that including it there would help learners ensure consistency and accuracy when reviewing the final result.

**Comment by julieplummer20** [comment]
Hi Fransisco,
You're absolutely right. Many thanks for all this feedback. I have incorporated the change. It should be visible soon.
Best wishes,
Julie.
