### ISSUE TITLE
Enhance an ABAP Core Data Services (CDS) View in SAP Business Technology Platform (BTP) ABAP Environment

### ISSUE THREAD

**Issue by allenchs78** [sap-tutorials/abap-core-development#2541]
Tutorials: https://developers.sap.com/tutorials/abap-environment-enhance-cds-view.html
--------------------------

Point not given to ymallen for Devtoberfest 2024.

**Comment by sheenamk** [comment]
Please ask the user to leave a comment on [Devtoberfest Group](https://community.sap.com/t5/devtoberfest-blog-posts/devtoberfest-2024-week-2-contest-activities/ba-p/13880856) and we can get it checked.

**Comment by julieplummer20** [comment]
Hi allench78, Could you please do as Sheena suggests? Since there is nothing we can do here, I am closing this issue.
Best wishes,
Julie Plummer.
