### ISSUE TITLE
Create an ABAP Core Data Services (CDS) View in SAP BTP, ABAP Environment

### ISSUE THREAD

**Issue by shilpashankar02** [sap-tutorials/abap-core-development#2548]
Tutorials: https://developers.sap.com/tutorials/abap-environment-create-cds-mde.html
--------------------------

Write here how you think we can improve the tutorial ...
Step 9: The code to enter in the CDS cannot end with key TravelID;. It should be key TravelID,
Step 9: The Code snippet to add the UI annotations should also include @Semantics.amount.currencyCode: 'CurrencyCode' for BookingFee and TotalPrice. Else it's easy to miss out and get the error.
Step 11: the annotation "@Semantics.currencyCode" for CurrencyCode cannot be used in the CDS View entity. In Step 2 we have defined CDS View Entity and not CDS View
Step 14: The code of the CDS shows Define view and not Define view entity

**Comment by julieplummer20** [comment]
Hi Shilpa, 
Am I correct in understanding that you and your colleagues added these corrections?
If not, please feel free to reopen.

Thanks a lot and best wishes,
Julie.
