### ISSUE TITLE
Providing Authorization Control for a Business Configuration Maintenance Object

### ISSUE THREAD

**Issue by nicksb555** [sap-tutorials/abap-core-development#438]
Tutorials: https://developers.sap.com/tutorials/abap-environment-authorization-control.html
--------------------------

Hi Patrick,

Great tutorial! 

In step 1 'Create IAM App' #11, I think the screenshot is misleading. As TABLNM for authorization 0002 'Display change documents', it shows ZERROR_CODE_000. The table name used in the tutorial is ZERRCODE_###.

Regards,
Dominik (Graus)

**Comment by sepp4me** [comment]
Hi Dominik,

you're right, thanks! fixed with #439 

Regards,
Patrick
