### ISSUE TITLE
Get Started with ABAP Development on-Premise

### ISSUE THREAD

**Issue by maxx69** [sap-tutorials/abap-core-development#440]
Mission: https://developers.sap.com/mission.abap-dev-get-started.html
--------------------------

Remember, there is no such thing as "on-premise" in real English.

"https://collectivecontent.agency/2018/04/19/should-i-say-on-premise-or-on-premises-it/"

**Comment by julieplummer20** [comment]
Hi Maxx69,
Thanks for your comment. "on-premise" is consistent with SAP Branding.
Best wishes,
Julie Plummer.
