### ISSUE TITLE
Create a Simple ABAP CDS View in ADT - some little inconsistencies

### ISSUE THREAD

**Issue by BaerbelW** [sap-tutorials/abap-core-development#442]
Tutorials: https://developers.sap.com/tutorials/abap-dev-adt-create-cds-view.html
--------------------------

While working through the tutorial, I noticed a few little inconsistencies:

**Step 2**
The instructions provide the names to use in the definition with adding a suffix:
![grafik](https://github.com/sap-tutorials/abap-core-development/assets/18588108/ffbf03ae-4f12-4680-bc73-2d8e442cc8bf)

**Step 3**
The screenshot shows different names (which might be confusing):
![grafik](https://github.com/sap-tutorials/abap-core-development/assets/18588108/355c4f5e-b8e0-4211-b1dc-7e1dd26bc9ab)

Some of the other screenshots also show different names.

**Step 8**
The instructions state to restrict the where-clause to currency "USD" but the sample test result shows entries with currency = "EUR":
![grafik](https://github.com/sap-tutorials/abap-core-development/assets/18588108/7569142b-48fa-4131-b045-b4ac9a851415)

Hope this helps!

Cheers
Bärbel

**Comment by julieplummer20** [comment]
Hi Bärbel,
Nice to hear from you. I have updated the tutorial accordingly; changes should appear soon.
Thanks and best wishes,
Julie.
