### ISSUE TITLE
Enhance the Business Object Behavior With Unmanaged Internal Numbering

### ISSUE THREAD

**Issue by seVladimirs** [sap-tutorials/abap-core-development#540]
Tutorials: https://developers.sap.com/tutorials/abap-environment-rap100-early-numbering.html
--------------------------

In `Step 2 point 2`, the statement says to `Set the cursor on the statement create; and press Ctrl+1 to open the Quick Assist view.` This only works on Windows machines. For MacOS, developers should use `Command+1`.

**Comment by mervey45** [comment]
Hi @seVladimirs ,

thank you for your comment. We'll update this as soon as possible.

Best regards, 
Merve
