### ISSUE TITLE
Create an HTTP Service in SAP BTP ABAP Environment

### ISSUE THREAD

**Issue by Nov05** [sap-tutorials/abap-core-development#70]
Tutorials: https://developers.sap.com/tutorials/abap-environment-create-http-service.html
--------------------------

Write here how you think we can improve the tutorial ...

Hi there. Thanks for the tutorial. 
I think there is a really minor issue.
For this line of code, ` |<p> Today, the date is:  { get_system_date }| &&`, it should be `system_date` rather than `get_system_date`.

```
  METHOD get_html.

    DATA(user_formatted_name) = cl_abap_context_info=>get_user_formatted_name( ).
    DATA(system_date) = cl_abap_context_info=>get_system_date( ).

    ui_html =  |<html> \n| &&
    |<body> \n| &&
    |<title>General Information</title> \n| &&
    |<p style="color:DodgerBlue;"> Hello there, { user_formatted_name } </p> \n | &&
    |<p> Today, the date is:  { get_system_date }| &&
    |<p> | &&
    |</body> \n| &&
    |</html> | .

  ENDMETHOD.
```

**Comment by julieplummer20** [comment]
Hi Nov05,
I think you're right. I'll just check this and update accordingly.
Thanks for getting in touch.
Best wishes,
Julie.
