### ISSUE TITLE
Create Table Persistence and Generate Data

### ISSUE THREAD

**Issue by mainakaich** [sap-tutorials/abap-core-development#84]
Tutorials: https://developers.sap.com/tutorials/abap-environment-persistence.html
--------------------------

1. Can you please clarify where the the newly created DB table is saved in cloud? Where the DB is located?
2. In this tutorial, we are not creating any explicit service instance to any DB e.g. HANA DB on cloud or anything similar. So I am interested to know which DB is used to store the data.
3. Additionally, it would be great if you can share is there any limitation of how much data can be stored in DB via the BTP ABAP Environment.

**Comment by mervey45** [comment]
Hi @mainakaich ,

SAP BTP,  ABAP environment is HANA only. Sizing options can be found here: https://blogs.sap.com/2022/02/23/sap-btp-abap-environment-release-2202/ 

Thank you.

Best regards, 
Merve
