### ISSUE TITLE
Maintain a Communication Arrangement for Outbound Communication #96

### ISSUE THREAD

**Issue by virengupta30** [sap-tutorials/abap-core-development#97]
Could not find the discussions tab to log a suggestion, so creating an issue here.

Like the tutorial "Maintain a Communication Arrangement for Inbound Communication https://developers.sap.com/tutorials/abap-environment-communication-arrangement.html" I feel there should be one for the outbound communication too - is there anything in pipeline?

**Comment by julieplummer20** [comment]
Hi Virengupta30,
This is not my mission; however, this appears to cover outbound comms from SAP S/4HANA Cloud to SAP BTP, ABAP Environment:
[Create Communication System to Connect to SAP BTP, ABAP Environment.](https://developers.sap.com/tutorials/abap-environment-s4hanacloud.html#c0cd2883-b309-4cd2-a423-8cd51abf4d60 )

This mission covers outbound comms from SAP BTP, ABAP Environment to an on-premise ABAP system by RFC: 
[Get Data from an On-Premise System Using a Remote Function Call (RFC)](https://developers.sap.com/mission.abap-env-connect-onpremise.html)

This mission covers outbound comms from SAP BTP, ABAP Environment to a Cloud system (here, a second instance of SAP BTP, ABAP Environment) by OData service:
[Get Data from a Remote System Using an OData Service](https://developers.sap.com/mission.abap-env-connect-2-environments.html)

All our tutorials for SAP BTP, ABAP Environment , including these are available here:
[SAP Tutorials: ABAP Development, SAP BTP, ABAP Environment](https://developers.sap.com/tutorial-navigator.html?tag=programming-tool%3Aabap-development&tag=software-product%3Atechnology-platform%2Fsap-business-technology-platform%2Fsap-btp-abap-environment).

HTH,
Julie Plummer.
SAP PM Team
